### ISSUE TITLE
Your Iris account could not be authenticated

### ISSUE THREAD

**Issue by alexruffell** [ivee/ivee#4]
Even though I do not have an Iris account, and I do not have any Iris devices, all I get when I ask Iris to turn something on or off is that my Iris account cannot be authenticated. I removed and reauthorized my Smartthings account but nothing changed. After updating some settings in the Hue lights section on the web I got it to turn them on but I can no longer turn them off.

**Comment by dhleong** [comment]
Got htis as well; I only have WeMo

**Comment by elmedico27** [comment]
I am also receiving this error when asking to turn WeMo switches on and off.  I do not have Iris.

**Comment by bensilver** [comment]
Hi all, we are working on the above issues and will get back shortly with a fix. Happy Holidays.

**Comment by alexruffell** [comment]
R.I.P. Ivee - I am unplugging mine for good.
